### ISSUE TITLE
Reference markers leak (stay after they shoud have disappeared)

### ISSUE THREAD

**Issue by radekn** [hax/refactor#10] opened 2015-09-21 11:10 UTC
I start renaming some local variable in javascript, and then cancel the rename (e.g. by pressing Escape, or move cursor outside of the variable name). After I move the cursor out of the variable name, the reference markers for this variable are still shown. If I repeat this process, I will end up with more of them overlaid on top of each other. There seems to be no way of getting them to disappear.

**Comment by borisdiakur** [comment] 2016-01-15 08:14
+1

**Comment by mindjuice** [comment] 2016-04-06 19:09
This is happening for me too.

![screen shot 2016-04-06 at 12 05 44 pm](https://cloud.githubusercontent.com/assets/934638/14329481/5ce1e94a-fbf0-11e5-98e0-cf1434e43f1d.png)

Pressing the shortcut key over and over causes the highlights to be added again each time too.

**Comment by Redsandro** [comment] 2016-04-11 12:30
I have the same issue. There are other ways of triggering this. Sometimes I don't know what I did, but they stay indeed.

**Comment by YarnSphere** [comment] 2016-04-27 20:14
This seems to happen to me when saving (pressing `Ctrl`+`S`) while the cursor is on some variable (and the marker is showing).

**Edit:** Apparently, the same happens when pressing `Ctrl`+`C` when the cursor is on a variable.

**Comment by livelazily** [comment] 2016-05-08 15:34
It can reproduce by pressing the rename shortcut (`ctrl-alt-r`) **more then twice** in the same variable, then move cursor outside of the variable by using mouse, the marker was still there.

**Comment by maboelsoud** [comment] 2016-06-01 23:45
ya it seems to be happening with me too. Whenever i press `cmd + s` or `cmd + c`

**Comment by hax** [comment] 2016-06-24 02:35
It should be fixed in 0.6.1+. If anyone see it again  ,pls reopen this issue.

**Closed as completed by hax** 2016-06-24 02:35 UTC
Labels: bug
